# Usar uma imagem base do OpenJDK 17 com Alpine
FROM openjdk:17-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo JAR gerado pelo Maven/Gradle
COPY target/todolist-0.0.1-SNAPSHOT.jar app.jar

# Informar qual porta o aplicativo vai usar
EXPOSE 8080

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]
