apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ivyson/todolist-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/todolist
            - name: SPRING_DATASOURCE_USERNAME
              value: "adm"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
